// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeKfnuf5RrLRRP6xPoZDJxEkYH0SN7Qxw',
    appId: '1:184522780384:web:cf938961744e8fc6ea6a85',
    messagingSenderId: '184522780384',
    projectId: 'hotel-booking-ee19d',
    authDomain: 'hotel-booking-ee19d.firebaseapp.com',
    storageBucket: 'hotel-booking-ee19d.appspot.com',
    measurementId: 'G-83KF58XHVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqLSOSbbqcO_7HjqKO8zcONrvy2P9TrTE',
    appId: '1:184522780384:android:8261b7cfff1a1d26ea6a85',
    messagingSenderId: '184522780384',
    projectId: 'hotel-booking-ee19d',
    storageBucket: 'hotel-booking-ee19d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb6DmW6Wk8INPkenxl-wwycOCgzyXIXg4',
    appId: '1:184522780384:ios:e834d7fbfe68912cea6a85',
    messagingSenderId: '184522780384',
    projectId: 'hotel-booking-ee19d',
    storageBucket: 'hotel-booking-ee19d.appspot.com',
    iosBundleId: 'com.example.hotelbooking.hotelBookingManagementSystem',
  );
}
